# Generated by Django 4.1.9 on 2023-10-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0002_category_type2_category_type3_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی داشبورد و چارت ها', 'verbose_name_plural': 'دسته بندی داشبورد و چارت ها'},
        ),
        migrations.AlterModelOptions(
            name='category_type2',
            options={'verbose_name': 'دسته بندی منبع داده', 'verbose_name_plural': 'دسته بندی منبع داده'},
        ),
    ]
