# Generated by Django 4.1.9 on 2024-01-04 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HamkavConfigurator', '0003_alter_category_options_alter_category_type2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('updated_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('def_id', models.IntegerField()),
                ('def_zone', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('idx', models.CharField(blank=True, max_length=300, null=True)),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
