# Generated by Django 4.1.9 on 2024-01-04 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HamkavConfigurator', '0004_definition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Definition',
            new_name='Definitions',
        ),
    ]
