# Generated by Django 4.1.9 on 2024-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0005_rename_definition_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitions',
            name='def_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='definitions',
            name='def_zone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='definitions',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
