# Generated by Django 4.1.9 on 2024-01-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0007_attribute_property_delete_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='user_creator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='user_creator',
        ),
    ]
