# Generated by Django 4.1.9 on 2024-01-12 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0009_attribute_user_creator_property_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
