# Generated by Django 4.1.9 on 2024-01-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0010_alter_attribute_uuid_alter_property_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='item_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='item_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
