# Generated by Django 4.1.9 on 2024-01-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0011_alter_attribute_item_name_alter_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='item_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='item_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
