# Generated by Django 4.1.9 on 2024-01-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0012_alter_attribute_item_code_alter_property_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='attribute',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
