# Generated by Django 4.1.9 on 2024-01-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0013_attribute_description_attribute_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='item_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='item_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
