# Generated by Django 4.1.9 on 2024-01-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HamkavConfigurator', '0014_alter_attribute_item_code_alter_property_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('updated_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_name', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='item_code',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='item_name',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='property',
        ),
        migrations.AddField(
            model_name='attributeitems',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HamkavConfigurator.attribute'),
        ),
        migrations.AddField(
            model_name='attributeitems',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
