# Generated by Django 4.1.9 on 2024-01-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0016_alter_attribute_id_alter_attributeitems_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeitems',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributeitems',
            name='user_creator',
        ),
        migrations.DeleteModel(
            name='attribute',
        ),
        migrations.DeleteModel(
            name='AttributeItems',
        ),
    ]
