# Generated by Django 4.1.9 on 2024-01-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0018_attribute_attributeitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeitems',
            old_name='item_name',
            new_name='item_code',
        ),
        migrations.AddField(
            model_name='attributeitems',
            name='item_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
