# Generated by Django 4.1.9 on 2024-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0019_rename_item_name_attributeitems_item_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeitems',
            name='item_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
