# Generated by Django 4.1.9 on 2024-01-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0020_attributeitems_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='attributeitems',
            name='item_name',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
