# Generated by Django 4.1.9 on 2023-06-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0010_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
