# Generated by Django 4.1.9 on 2023-06-23 03:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0014_rename_title_category_label_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
