# Generated by Django 4.1.9 on 2023-06-23 06:03

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0015_post_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
