# Generated by Django 4.1.9 on 2023-06-25 14:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0016_alter_post_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
