# Generated by Django 4.1.9 on 2023-06-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0017_alter_post_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
