# Generated by Django 4.1.9 on 2023-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0018_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brife',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
