# Generated by Django 4.1.9 on 2023-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0019_post_brife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brife',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
