# Generated by Django 4.1.9 on 2023-06-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0021_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2_post', to='HamkavBlog.category2'),
        ),
    ]
