# Generated by Django 4.1.9 on 2023-06-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0025_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_shamsi',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_shamsi',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
