# Generated by Django 4.1.9 on 2023-07-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0028_post_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_active',
            new_name='is_deleted',
        ),
    ]
