# Generated by Django 4.1.9 on 2023-07-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavBlog', '0032_post_is_restricted_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='is_published',
        ),
    ]
