# Generated by Django 4.1.9 on 2023-11-20 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0003_alter_category_options_alter_category_type2_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HamkavMedia', '0002_rename_image_url_imagesmodel_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('media_url', models.ImageField(upload_to='attach/%Y/%m/%d')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('access', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('updated_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_category', to='HamkavConfigurator.category_type3')),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageTypeModel',
            new_name='MediaTypeModel',
        ),
        migrations.DeleteModel(
            name='ImagesModel',
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Media_MediaType', to='HamkavMedia.mediatypemodel'),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
