# Generated by Django 4.1.9 on 2023-06-15 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_sent_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(blank=True, max_length=500, null=True)),
                ('recipient_number', models.CharField(max_length=12)),
                ('message_id', models.CharField(blank=True, max_length=15, null=True)),
                ('message_cost', models.FloatField(blank=True, null=True)),
                ('pattern_code', models.CharField(blank=True, max_length=50, null=True)),
                ('recipent_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sms_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_sending_sms', models.BooleanField(default=True)),
                ('allowed_sending_groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('allowed_sending_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_url', models.CharField(blank=True, max_length=500, null=True)),
                ('actor_object_id', models.PositiveIntegerField()),
                ('sender_object_id', models.PositiveIntegerField()),
                ('unread', models.PositiveSmallIntegerField(default=1)),
                ('public', models.PositiveSmallIntegerField(default=0)),
                ('email', models.PositiveSmallIntegerField(default=0)),
                ('sms', models.PositiveSmallIntegerField(default=0)),
                ('push', models.PositiveSmallIntegerField(default=0)),
                ('panel', models.PositiveSmallIntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor_content_type', to='contenttypes.contenttype')),
                ('recipent_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipent_group', to='auth.group')),
                ('recipent_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipent_user', to=settings.AUTH_USER_MODEL)),
                ('sender_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender_content_type', to='contenttypes.contenttype')),
            ],
        ),
    ]
