# Generated by Django 4.1.9 on 2023-07-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_welcomepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='welcomePage',
        ),
    ]
