# Generated by Django 4.1.9 on 2023-08-15 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavAuth', '0005_user_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
