# Generated by Django 4.1.9 on 2023-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0003_chartmodel_chart_type_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartmodel',
            old_name='chart_type_access',
            new_name='chart_access',
        ),
    ]
