# Generated by Django 4.1.9 on 2023-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0004_rename_chart_type_access_chartmodel_chart_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartmodel',
            name='chart_type_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
