# Generated by Django 4.1.9 on 2023-08-31 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HamkavDashboard', '0005_alter_chartmodel_chart_type_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartmodel',
            old_name='chart_type_title',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='chartmodel',
            old_name='chart_additional_config',
            new_name='extra_config',
        ),
        migrations.RemoveField(
            model_name='chartmodel',
            name='chart_access',
        ),
        migrations.RemoveField(
            model_name='chartmodel',
            name='chart_base_config',
        ),
        migrations.RemoveField(
            model_name='chartmodel',
            name='chart_type_id',
        ),
        migrations.RemoveField(
            model_name='chartmodel',
            name='name',
        ),
        migrations.CreateModel(
            name='ChartTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('access', models.CharField(blank=True, max_length=300, null=True)),
                ('base_config', models.JSONField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('updated_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chartmodel',
            name='chart_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HamkavDashboard.charttypemodel'),
        ),
    ]
