# Generated by Django 4.1.9 on 2023-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0007_charttypemodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartmodel',
            name='chart_type_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
