# Generated by Django 4.1.9 on 2023-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0009_remove_chartmodel_chart_type_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartmodel',
            name='chart_type_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
