# Generated by Django 4.1.9 on 2023-09-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0010_chartmodel_chart_type_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartmodel',
            name='chart_type_title',
        ),
    ]
