# Generated by Django 4.1.9 on 2023-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0011_remove_chartmodel_chart_type_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttypemodel',
            name='meta_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
