# Generated by Django 4.1.9 on 2023-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0013_layoutmodel_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutmodel',
            name='layout_config',
            field=models.TextField(null=True),
        ),
    ]
