# Generated by Django 4.1.9 on 2023-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0014_alter_layoutmodel_layout_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutmodel',
            name='layout_config',
            field=models.JSONField(blank=True, max_length=2000, null=True),
        ),
    ]
