# Generated by Django 4.1.9 on 2023-09-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0006_databasetype_created_shamsi_and_more'),
        ('HamkavDashboard', '0017_alter_layoutmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartmodel',
            name='datasource',
        ),
        migrations.AddField(
            model_name='chartmodel',
            name='datasource',
            field=models.ManyToManyField(to='HamkavDbManagement.datasourcemodel'),
        ),
    ]
