# Generated by Django 4.1.9 on 2023-09-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0001_initial'),
        ('HamkavDashboard', '0018_remove_chartmodel_datasource_chartmodel_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_category', to='HamkavConfigurator.category'),
        ),
    ]
