# Generated by Django 4.1.9 on 2023-09-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0020_chartmodel_category_alter_layoutmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartmodel',
            name='category',
        ),
    ]
