# Generated by Django 4.1.9 on 2023-09-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDashboard', '0022_chartmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutmodel',
            name='category',
        ),
    ]
