# Generated by Django 4.1.9 on 2023-09-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavConfigurator', '0002_category_type2_category_type3_alter_category_name'),
        ('HamkavDashboard', '0024_layoutmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_category', to='HamkavConfigurator.category'),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_category', to='HamkavConfigurator.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
