# Generated by Django 4.1.9 on 2023-08-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnectionmodel',
            name='type',
        ),
    ]
