# Generated by Django 4.1.9 on 2023-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnectionmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
