# Generated by Django 4.1.9 on 2023-08-21 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HamkavDbManagement', '0004_alter_databaseconnectionmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnectionmodel',
            name='created_shamsi',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnectionmodel',
            name='updated_shamsi',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DataSourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('query_string', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('updated_shamsi', models.CharField(editable=False, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HamkavDbManagement.databaseconnectionmodel')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
