# Generated by Django 4.1.9 on 2023-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0007_databaseconnectionmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemodel',
            name='query_string',
            field=models.TextField(null=True),
        ),
    ]
