# Generated by Django 4.1.9 on 2023-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0009_datasourcemodel_media_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemodel',
            name='datasource_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
