# Generated by Django 4.1.9 on 2023-11-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0011_remove_datasourcemodel_datasource_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemodel',
            name='datasource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HamkavDbManagement.datasourcetype'),
        ),
    ]
