# Generated by Django 4.1.9 on 2023-11-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0012_datasourcemodel_datasource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemodel',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcemodel',
            name='query_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
