# Generated by Django 4.1.9 on 2023-11-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavMedia', '0003_mediamodel_rename_imagetypemodel_mediatypemodel_and_more'),
        ('HamkavDbManagement', '0013_alter_datasourcemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemodel',
            name='media_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HamkavMedia.mediamodel'),
        ),
    ]
