# Generated by Django 4.1.9 on 2024-01-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamkavDbManagement', '0016_alter_datasourcemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemodel',
            name='name',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
